name: Regular Nix Flake Update

on:
  schedule:
    # Run at midnight every day
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: nix-flake-update
  cancel-in-progress: true

jobs:
  update-and-build:
    runs-on: macos-15
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: List directory
        run: |
          pwd
          ls -la

      - name: Cache Nix store
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: /nix/store
          key: store-${{ runner.os }}-${{ hashFiles('flake.lock') }}
          restore-keys: |
            store-${{ runner.os }}-

      - name: Install Nix
        uses: cachix/install-nix-action@v31.8.4
        with:
          extra_nix_config: |
            secret-key-files = ${{ github.workspace }}/cache-priv-key.pem

      - name: Configure Nix for signing
        run: |
          echo '${{ secrets.CACHE_PRIVATE_KEY }}' > cache-priv-key.pem
          chmod 600 cache-priv-key.pem

      - name: Update flake.lock
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: nix flake update

      - name: Build darwin configuration
        run: nix build .#darwinConfigurations.trv4250.config.system.build.toplevel

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3 # v7.0.0
        with:
          commit_message: 'chore: update flake.lock'
          file_pattern: flake.lock

      - name: Publish to binary cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          nix copy --to 's3://${{ secrets.CACHE_URL }}' .#darwinConfigurations.trv4250.config.system.build.toplevel

      - name: Show storage size
        run: |
          nix path-info --json --all | jq 'map(.narSize) | add' | numfmt --to=iec-i
