name: Test Flake

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-and-build:
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Cache Nix store
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: nix-cache.bin
          key: store-${{ runner.os }}-${{ hashFiles('flake.lock') }}
          restore-keys: |
            store-${{ runner.os }}-

      - name: Install Nix
        uses: cachix/install-nix-action@v31.8.4
        with:
          extra_nix_config: |
            accept-flake-config = true
            download-buffer-size = 524288000

      - name: Check flake
        run: nix flake check

      - name: Unpack local binary cache
        run: |
          nix copy --from 'file://./nix-cache.bin?compression=zstd&parallel-compression=true' --all

      - name: Build darwin configuration
        run: nix build .#darwinConfigurations.trv4250.config.system.build.toplevel

      - name: Updated local binary cache
        run: |
          nix copy --to 'file://./nix-cache.bin?compression=zstd&parallel-compression=true' .#darwinConfigurations.trv4250.config.system.build.toplevel
