name: Test Flake

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NIX_CACHE_PATH: ${{ github.workspace }}/nix-cache.bin
  NIX_CACHE_URL: file://${{ github.workspace }}/nix-cache.bin?compression=zstd&parallel-compression=true
  DARWIN_CONFIG: .#darwinConfigurations.trv4250.config.system.build.toplevel

jobs:
  check-and-build:
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Cache Nix sources
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.cache/nix
          key: nix-cache-${{ hashFiles('flake.lock') }}

      - name: Cache Nix store
        id: cache-nix-store
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: '${{ env.NIX_CACHE_PATH }}'
          key: store-${{ runner.os }}-${{ hashFiles('flake.lock') }}
          restore-keys: |
            store-${{ runner.os }}-

      - name: Install Nix
        uses: cachix/install-nix-action@v31.8.4
        with:
          extra_nix_config: |
            accept-flake-config = true
            download-buffer-size = 524288000
            substituters = file://${{ github.workspace }}/nix-cache.bin?trusted=1 https://cache.nixos.org

      - name: Check flake
        run: nix flake check

      - name: Build darwin configuration
        run: nix build '${{ env.DARWIN_CONFIG }}'

      - name: Set local binary cache permissions
        run: |
          sudo chown -R $(whoami) '${{ env.NIX_CACHE_PATH }}'

      - name: Updated local binary cache
        run: nix copy --to '${{ env.NIX_CACHE_URL }}' '${{ env.DARWIN_CONFIG }}'
